version: "3.8"
services:
  mongo:
    image: mongo:7
    container_name: pct-mongo
    volumes: ["mongo-data:/data/db"]
    ports:
      - "27017:27017"
    restart: unless-stopped

  api:
    build: ./capstone-api
    container_name: pct-api
    depends_on:
      - mongo
    ports:
      - "4000:4000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/policy-claims
      - JWT_SECRET=${JWT_SECRET:-change-me-in-production}
      - PORT="4000"
      - NODE_ENV=production
    restart: unless-stopped
  client:
    build: ./capstone-client
    container_name: pct-client
    depends_on:
      - api
    ports:
      - "8443:443"
      - "8080:80"
    volumes:
      - ./certs:/etc/nginx/certs:ro          # (1)
      - ./capstone-client/nginx-ssl.conf:/etc/nginx/conf.d/default.conf:ro  # (2)
    restart: unless-stopped

volumes:
  mongo-data: