apiVersion: v1
kind: Secret
metadata:
  name: policy-claims-secrets
  namespace: policy-claims
type: Opaque
data:
  JWT_SECRET: dGVzdC1zZWNyZXQ=
  MONGODB_URI: bW9uZ29kYjovL21vbmdvOjI3MDE3L3BvbGljeS1jbGFpbXM=
